---
title: "PLAY-planning"
author: "Rick O. Gilmore & David Millman"
date: "`r Sys.time()`"
output:
  github_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

## Roles

### Databrary Authorized Investigators (Databrary AIs)

- Any Authorized Investigator on Databrary

### PLAY Authorized Investigators (PLAY AI)

### All Databrary Authorized Investigators who are also contributing to the PLAY Project

### PLAY Principal Investigators (PIs): Karen (KEA), Cathie (CTL), Rick (ROG)

### PLAY Staff

#### Language Transcription and Behavioral Coding Manager (Coding Manager)

#### Protocol and Quality Assurance Manager (QA Manager)

####  Datavyu Manager

### Data Collector

- AI or PIs

### Data Coder

- AI or PIs

### Research Assistants (RAs)

- Graduate students, undergraduates, or research staff under the supervision of Data Collector or Data Coder 

## Technical Concepts

### Volume

- A container for data collection sessions, materials, and metadata related to a research study or project.

### Superset

- A collection of sessions across volumes that are related to one another in some way. The data shared from the PLAY Project will be a Superset because it contains sessions across a set of volumes that the Data Collectors owned and used to upload videos.

### Spreadsheet

- A container for storing sessions and metadata about the participants, setting, and tasks associated with one or more sessions

### Session

- A container for storing component(s) and linked to data that represents some people measured in a place on a particular time

### Component

- A video or data file associated with a session

### Coding pass

- The efforts of a Data Coder or Research Assistant supervised by a Data Coder that generates a Datavyu file with codes that are time-locked to a video
    - What information in what format goes in the Datavyu file? Info about the Databrary volume the file is linked to? etc.
- All PLAY free-play videos will get coding passes for these domains:
    - Locomotion and Physical Activity
    - Object Interaction
    - Emotional Expression
    - Language
- The Language pass must follow the Transcription pass

### Queue

- A list-like or array like structure that contains links to resources that are assigned to a person for a particular purpose (e.g., QA checking, coding, etc.)



#### Coding Manager assigns videos that pass QA for coding & transcription

##### Constraints

- Data Coders should not be assigned to videos for which they were the Data Collector
- Coding passes for the same video may be assigned in parallel
- Transcription must be completed (and reliability checked) before Language pass can be assigned

##### Questions (Policy)

- Should metadata about which labs coded a given pass be collected? Should those be stored? Shared, if so with whom? Coding Lab PI can upload or replace Datavyu spreadsheeet, but not delete, and not contribute other data.

### Data Coders upload transcriptions and/or coding files to Databrary

- As Data Coder, I want to upload the Datavyu file from my coding pass to Databrary. 

#### Questions

- Where do Data Coders upload transcriptions and/or coding files?
- How do PLAY Staff get notified that a transcription or coding file is ready for reliability checking?

### PLAY PIs share PLAY Superset and Additional Data Superset with all PLAY AIs

#### Timing

- Middle of Year 4 (~2016-10-01)

### PLAY PIs share PLAY volume with all Databrary AIs

- Timing: End of grant period, 2012-04-01?

